databases:
  - name: drugtracedb
    plan: free
    databaseName: drugtrace
    user: drugtrace

services:
  - type: web
    plan: free
    name: drugtrace
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn DrugTraceApp.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drugtracedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 