# Generated by Django 3.2.24 on 2025-05-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DrugTraceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactured_drugs', to='DrugTraceApp.user'),
        ),
        migrations.AlterField(
            model_name='drugtrace',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_traces', to='DrugTraceApp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='drugtraceapp_user_set', related_query_name='drugtraceapp_user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='drugtraceapp_user_set', related_query_name='drugtraceapp_user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
